name: Create library release archives, create a GH release and publish PyPI wheel and sdist on tag in main branch


# This is executed automatically on a tag in the main branch

# Summary of the steps:
# - build wheels and sdist
# - upload wheels and sdist to PyPI
# - create gh-release and upload wheels and dists there
# TODO: smoke test wheels and sdist
# TODO: add changelog to release text body

# WARNING: this is designed only for packages building as pure Python wheels

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-pypi-distribs:
    name: Build and publish library to PyPI
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Upload built archives
        uses: actions/upload-artifact@v3
        with:
          name: pypi_archives
          path: dist/*


  create-gh-release:
    name: Create GH release
    needs:
      - build-pypi-distribs
    runs-on: ubuntu-22.04

    steps:
      - name: Download built archives
        uses: actions/download-artifact@v3
        with:
          name: pypi_archives
          path: dist

      - name: Create GH release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/*


  create-pypi-release:
    name: Create PyPI release
    needs:
      - create-gh-release
    runs-on: ubuntu-22.04

    steps:
      - name: Download built archives
        uses: actions/download-artifact@v3
        with:
          name: pypi_archives
          path: dist

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
